### ISSUE TITLE
no such module placenoteSDK

### ISSUE THREAD

**Issue by xqyi** [Placenote/PlacenoteSDK-iOS#24]
hi 
i got an error when i try to run this sample app on my ipad pro: no such module placenoteSDK.
![tim 20180307165001](https://user-images.githubusercontent.com/3350573/37082495-ad49081e-2227-11e8-80e1-00c65a919057.png)

**Comment by xqyi** [comment]
BTW, i can build and run this app you posted: https://github.com/pmukherj/PlacenoteSDK-Planes/tree/simpleShape

**Comment by nmathew87** [comment]
Hi @xqyi, For the first issue with the sample code, you need to open the xcworkspace file in XCode and build that instead of the xcproject file. 
Could you check out these installation instructions and see if it fixes your issues?
https://placenote.com/install/scenekit

Let me know!

**Comment by y22ma** [comment]
@xqyi I think we got the bottom of the issue. The framework in the repo was wrong in a past commit, please pull again and try. With regards to the Plane sample app, please don't use that for now. It's an ongoing project and we'll release it in the future, but it's not ready for prime time yet.

**Comment by pmukherj** [comment]
Hey @xqyi if you want to try the PlacenoteSDK-Planes sample app for just placing a simple shape like in the blog, do make sure to run through the git lfs instructions. We have large files that are stored using git lfs and if you don't have them in the repo, you can see that "malloc" error. 

To run git lfs just run, 
git lfs install 
git lfs pull

**Comment by xqyi** [comment]
@y22ma i download this sample app again. also open xcworkspace file instead of a xcproject file in XCode, but i got 15 errors when i build the project:
Undefined symbols for architecture arm64:
  "_PNSetFrame", referenced from:
      _setFrameNative in LibPlacenote.o
  "_PNGetPose", referenced from:
      _getPoseNative in LibPlacenote.o
  "_PNGetStatus", referenced from:
      __T012PlacenoteSDK03LibA0C16getMappingStatusAC0eF0OyFTf4d_n in LibPlacenote.o
  "_PNInitialize", referenced from:
      _initializeSDK in LibPlacenote.o
  "_PNStartRecordDataset", referenced from:
      __T012PlacenoteSDK03LibA0C17startReportRecordyySb_SbSftc16uploadProgressCb_tF in LibPlacenote.o
  "_PNSaveMap", referenced from:
      __T012PlacenoteSDK03LibA0C7saveMapyySSSgc7savedCb_ySb_SbSftc014uploadProgressG0tFySpySC18PNCallbackResult_tVGSg_SvSgtcfU_ in LibPlacenote.o
  "_PNAddMap", referenced from:
      __T012PlacenoteSDK03LibA0C7saveMapyySSSgc7savedCb_ySb_SbSftc014uploadProgressG0tF in LibPlacenote.o
  "_PNListMaps", referenced from:
      __T012PlacenoteSDK03LibA0C12fetchMapListyySb_SaySSGtc6listCb_tF in LibPlacenote.o
  "_PNStopSession", referenced from:
      __T012PlacenoteSDK03LibA0C11stopSessionyyF in LibPlacenote.o
  "_PNGetTrackedLandmarks", referenced from:
      __T012PlacenoteSDK03LibA0C19getTrackedLandmarksSaySC16PNFeaturePoint_tVGyF in LibPlacenote.o
  "_PNLoadMap", referenced from:
      __T012PlacenoteSDK03LibA0C7loadMapySS5mapId_ySb_SbSftc18downloadProgressCbtF in LibPlacenote.o
  "_PNDeleteMap", referenced from:
      __T012PlacenoteSDK03LibA0C9deleteMapySS5mapId_ySbc9deletedCbtF in LibPlacenote.o
  "_PNStartSession", referenced from:
      __T012PlacenoteSDK03LibA0C12startSessionyyF in LibPlacenote.o
  "_PNGetAllLandmarks", referenced from:
      __T012PlacenoteSDK22FeaturePointVisualizerC14drawPointcloud33_B5330B43343F95DEC8BEB9579B8AF455LLyyF in FeaturePointVisualizer.o
      __T012PlacenoteSDK03LibA0C15getAllLandmarksSaySC16PNFeaturePoint_tVGyF in LibPlacenote.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

![tim 20180306082334](https://user-images.githubusercontent.com/3350573/37237254-24661362-244c-11e8-93b3-c460f26fb74e.png)

btw i use vmware14+macos 10.13 as dev envrionment.

**Comment by pmukherj** [comment]
Hey @xqyi, 
Sorry you are having trouble with this. Can I ask what version of iPad Pro and iOS version installed you are using?

**Comment by y22ma** [comment]
Closing this issue, as the ticket author is not available to respond.

**Comment by KheniDharmesh** [comment]
It's strange because I have connected my device with system and try to run it and all errors removed.

**Comment by kmdnampoothiri** [comment]
I am getting exactly same issue. I have tried copy SDK from existing Placenote sample application. Still not working. 8.3 MB is the size of Placenote.framework.

Here is the log;

Undefined symbols for architecture arm64:
"_PNSetFrame", referenced from:
_setFrameNative in LibPlacenote.o
"_PNGetPose", referenced from:
_getPoseNative in LibPlacenote.o
"_PNSetIntrinsics", referenced from:
_setIntrinsicsNative in LibPlacenote.o
"_PNInitialize", referenced from:
_initializeSDK in LibPlacenote.o
"_PNStartRecordDataset", referenced from:
PlacenoteSDK.LibPlacenote.startReportRecord(uploadProgressCb: (Swift.Bool, Swift.Bool, Swift.Float) -> ()) -> () in LibPlacenote.o
"_PNGetMetadata", referenced from:
PlacenoteSDK.LibPlacenote.getMapMetadata(mapId: Swift.String, getMetadataCb: (Swift.Bool, PlacenoteSDK.LibPlacenote.MapMetadata) -> ()) -> () in LibPlacenote.o
"_PNListMaps", referenced from:
PlacenoteSDK.LibPlacenote.fetchMapList(listCb: (Swift.Bool, [Swift.String : PlacenoteSDK.LibPlacenote.MapMetadata]) -> ()) -> () in LibPlacenote.o
"_PNGetAllLandmarks", referenced from:
PlacenoteSDK.LibPlacenote.getAllLandmarks() -> [__C.PNFeaturePoint_t] in LibPlacenote.o
"_PNSearchMaps", referenced from:
PlacenoteSDK.LibPlacenote.searchMaps(searchParams: PlacenoteSDK.LibPlacenote.MapSearch, listCb: (Swift.Bool, [Swift.String : PlacenoteSDK.LibPlacenote.MapMetadata]) -> ()) -> () in LibPlacenote.o
"_PNSaveMap", referenced from:
closure #1 (Swift.UnsafeMutablePointer<__C.PNCallbackResult_t>?, Swift.UnsafeMutableRawPointer?) -> () in PlacenoteSDK.LibPlacenote.saveMap(savedCb: (Swift.String?) -> (), uploadProgressCb: (Swift.Bool, Swift.Bool, Swift.Float) -> ()) -> () in LibPlacenote.o
"_PNAddMap", referenced from:
PlacenoteSDK.LibPlacenote.saveMap(savedCb: (Swift.String?) -> (), uploadProgressCb: (Swift.Bool, Swift.Bool, Swift.Float) -> ()) -> () in LibPlacenote.o
"_PNStopSession", referenced from:
PlacenoteSDK.LibPlacenote.stopSession() -> () in LibPlacenote.o
"_PNShutdown", referenced from:
PlacenoteSDK.LibPlacenote.shutdown() -> () in LibPlacenote.o
"_PNGetStatus", referenced from:
PlacenoteSDK.LibPlacenote.getMappingStatus() -> PlacenoteSDK.LibPlacenote.MappingStatus in LibPlacenote.o
"_PNGetTrackedLandmarks", referenced from:
PlacenoteSDK.LibPlacenote.getTrackedLandmarks() -> [__C.PNFeaturePoint_t] in LibPlacenote.o
"_PNLoadMap", referenced from:
PlacenoteSDK.LibPlacenote.loadMap(mapId: Swift.String, downloadProgressCb: (Swift.Bool, Swift.Bool, Swift.Float) -> ()) -> () in LibPlacenote.o
"_PNSetMetadata", referenced from:
PlacenoteSDK.LibPlacenote.setMapMetadata(mapId: Swift.String, metadata: PlacenoteSDK.LibPlacenote.MapMetadataSettable, metadataSavedCb: (Swift.Bool) -> ()) -> Swift.Bool in LibPlacenote.o
"_PNDeleteMap", referenced from:
PlacenoteSDK.LibPlacenote.deleteMap(mapId: Swift.String, deletedCb: (Swift.Bool) -> ()) -> () in LibPlacenote.o
"_PNStartSession", referenced from:
PlacenoteSDK.LibPlacenote.startSession(extend: Swift.Bool) -> () in LibPlacenote.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
