### ISSUE TITLE
Must I have to resign the Placenote.framework?

### ISSUE THREAD

**Issue by JeremyRenner** [Placenote/PlacenoteSDK-iOS#36]
I build and run in my iPad.But the debuggershows:

dyld: Library not loaded: @rpath/Placenote.framework/Placenote
  Referenced from: /var/containers/Bundle/Application/DCFED95C-AB98-43F5-9C65-CFE00D9F2D19/placenote.app/placenote
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/DCFED95C-AB98-43F5-9C65-CFE00D9F2D19/placenote.app/Frameworks/Placenote.framework/Placenote: code signing blocked mmap() of '/private/var/containers/Bundle/Application/DCFED95C-AB98-43F5-9C65-CFE00D9F2D19/placenote.app/Frameworks/Placenote.framework/Placenote'
Message from debugger: Terminated due to signal 6

Is it a signature problem? Please save me- -

**Comment by pmukherj** [comment]
Hey @JeremyRenner,

Looks like you are having trouble code-signing our library. This may be related to your developer certificate settings. Some others have this problem with other dynamic libraries.

https://egeek.me/2017/10/21/code-signing-blocked-mmap-on-ios-device/

Do give this a shot.

**Comment by JeremyRenner** [comment]
I tried.It doesn’t solve my problem.......
